---
# defaults file for mariadb

login_unix_socket: /var/run/mysqld/mysqld.sock
login_user: root
login_password: root
mysql_remove_test_database: true
mysql_remove_anonymous_users: true
mysql_secure_installation: false
demote: true
purge_cluster: false
