[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$RBIt.4za$4PH2Rtp.9d6NsGUGJL6kv1"
  ]

[http.routers.api]
  rule = "Host(`192.168.67.75`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
