---
# Setup hosts

- name: Add hosts in /etc/hosts 
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  loop:
    - { name: ubuntu1, ip: 192.168.1.11 }
    - { name: ubuntu2, ip: 192.168.1.12 }
    - { name: ubuntu3, ip: 192.168.1.13 }
  
