---
# Installation of Elasticsearch

- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Add Elasticsearch signing key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repo
  copy:
    dest: "/etc/apt/sources.list.d/elastic-7.x.list"
    content: |
      deb https://artifacts.elastic.co/packages/7.x/apt stable main

- name: Install Elasticsearch verion '7.8.0'
  apt:
    update_cache: true
    name:
      - apt-transport-https 
      - elasticsearch=7.8.0
  notify: Restart Elasticsearch

  
